using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OpenTK;
using Orion.Engine;
using Orion.Engine.Collections;
using Orion.Game.Simulation;
using Orion.Game.Simulation.Components;

namespace Orion.Game.Simulation
{
    /// <summary>
    /// Initializes <see cref="World"/> instances with terrain and entity content.
    /// </summary>
    public abstract class WorldBuilder
    {
        #region Properties
        /// <summary>
        /// Gets the fixed size of the world generated by this generator.
        /// If <c>null</c>, indicates that the user can choose a world size.
        /// </summary>
        public virtual Size? FixedSize
        {
            get { return null; }
        }
        #endregion
        
        #region Methods
        /// <summary>
        /// Initializes the terrain and entities of a world instance.
        /// </summary>
        /// <param name="world">The world to be filled.</param>
        /// <param name="prototypes">The entity prototype registry.</param>
        public abstract void Build(World world, PrototypeRegistry prototypes);

        protected Entity CreateResourceNode(World world, PrototypeRegistry prototypes, 
            ResourceType type, Point location)
        {
            Entity entity = world.Entities.CreateEmpty();

            entity.SpecializeWithPrototype(prototypes.FromResourceType(type));
            entity.Spatial.Position = location;
            world.Entities.Add(entity);

            return entity;
        }
        #endregion
    }
}
